type Locale = "zh" | "en" | "ja";

const ZH = {
  units: "台",
  oversell: "⚠ 车辆库存不足，存在超售风险",
  fleetHint: "纵轴为时段，横轴为日期。格子显示剩余 / 总可用车辆，不按车号排列。",
  prevWeek: "上一周",
  nextWeek: "下一周",
  thisWeek: "本周",
  closed: "不可订",
  utilization: "车辆使用率",
  utilizationHint: "已预订车位 ÷ 总可用车位",
  included: "内置（套餐已含）",
  includedHint: "打开后前台直接列出，顾客无需加购。",
  allowed: "可加购",
  addonsMenu: "附加项管理",
  addonsLead: "独立管理附加项。可改名称、价格、描述、数量上限和上下架。",
  plansLead: "编辑套餐，并用开关标记哪些附加项已包含在套餐内。",
  inventoryLead: "按日期 × 时段查看可用车辆总数。",
  permissions: "权限配置",
  permissionsLead: "超管可建角色并分配查看 / 编辑权限。店长可给本店员工调配权限。刷新后立即生效。",
  permView: "查看",
  permEdit: "编辑",
  newRole: "新建角色",
  roleName: "角色名称",
  assignStaff: "员工权限",
  savePerms: "保存权限",
  permSaved: "权限已更新，刷新页面即生效。",
  completeOnlyManager: "「已完成」需店长或超管确认。",
  cancelKind: "取消类型",
  voluntary: "主动取消",
  noshow: "No-show（未到店）",
  channelFilter: "渠道",
  affiliateFilter: "推广代理",
  allAffiliates: "全部代理",
  affiliateField: "推广代理",
  affiliateNone: "无",
  refundAction: "退款操作",
  refundReserved: "退款规则待甲方确认后接入。此处仅预留操作与记录。",
  refundPolicy: "退款政策",
  refundPolicyLead: "填写前台/客服可见的退款说明文本。具体扣款逻辑稍后接入。",
  refundPolicyPh: "出发前 24 小时取消退 50%。出发前不足 24 小时或 No-show 不退款。",
  refundSaved: "退款政策已保存",
  refundNote: "退款备注",
  refundLog: "退款记录",
  refundEmpty: "暂无退款记录",
  pendingList: "待确认（不计营收）",
  cancelledList: "已取消（不计营收）",
  netIncome: "渠道净收入",
  affiliateTab: "代理佣金",
  affiliateTabHint: "第三批接入代理订单后，此处按代理汇总订单数 / 金额 / 应发佣金。",
  lastYear: "去年同月",
  cancelSplit: "取消构成",
  photos: "照片",
  photosHint: "可上传维修单据或损伤照片，支持多图。",
  active: "上架",
};

const EN: typeof ZH = {
  units: "karts",
  oversell: "⚠ Kart inventory is short. Oversell risk.",
  fleetHint: "Rows are time slots, columns are dates. Each cell shows remaining / total karts.",
  prevWeek: "Previous week",
  nextWeek: "Next week",
  thisWeek: "This week",
  closed: "Closed",
  utilization: "Kart utilization",
  utilizationHint: "Booked seats ÷ available seats",
  included: "Included in plan",
  includedHint: "Shown as included. Guests do not purchase these.",
  allowed: "Optional extras",
  addonsMenu: "Add-ons",
  addonsLead: "Edit name, price, description, quantity cap, and listing status.",
  plansLead: "Edit plans and mark which add-ons are already included.",
  inventoryLead: "Available karts by date and time slot.",
  permissions: "Permissions",
  permissionsLead: "Admins create roles. Managers can grant or revoke access for their staff. Changes apply on refresh.",
  permView: "View",
  permEdit: "Edit",
  newRole: "New role",
  roleName: "Role name",
  assignStaff: "Staff access",
  savePerms: "Save permissions",
  permSaved: "Permissions saved. Refresh to apply.",
  completeOnlyManager: "Only a manager or admin can mark an order completed.",
  cancelKind: "Cancel type",
  voluntary: "Guest cancelled",
  noshow: "No-show",
  channelFilter: "Channel",
  affiliateFilter: "Affiliate",
  allAffiliates: "All affiliates",
  affiliateField: "Affiliate",
  affiliateNone: "None",
  refundAction: "Refund",
  refundReserved: "Refund rules will be filled in after the client confirms them.",
  refundPolicy: "Refund policy",
  refundPolicyLead: "Policy text for staff and guests. Charge logic comes later.",
  refundPolicyPh: "Cancel 24h before departure: 50% refund. Inside 24h or no-show: no refund.",
  refundSaved: "Refund policy saved",
  refundNote: "Refund note",
  refundLog: "Refund log",
  refundEmpty: "No refund records yet",
  pendingList: "Pending (not in revenue)",
  cancelledList: "Cancelled (not in revenue)",
  netIncome: "Net after channel cut",
  affiliateTab: "Affiliate commission",
  affiliateTabHint: "Batch 3 will fill order count / amount / commission per affiliate.",
  lastYear: "Same month last year",
  cancelSplit: "Cancellations",
  photos: "Photos",
  photosHint: "Repair slips or damage photos. Multiple images allowed.",
  active: "Listed",
};

const JA: typeof ZH = {
  units: "台",
  oversell: "⚠ 車両在庫が不足しています。オーバーセルの恐れがあります。",
  fleetHint: "縦軸は時間、横軸は日付。マスは残数／総台数です。",
  prevWeek: "前週",
  nextWeek: "翌週",
  thisWeek: "今週",
  closed: "受付不可",
  utilization: "車両稼働率",
  utilizationHint: "予約席数 ÷ 提供席数",
  included: "セットに含む",
  includedHint: "オンにするとフロントに含まれている表示になり、追加購入しません。",
  allowed: "追加オプション",
  addonsMenu: "オプション管理",
  addonsLead: "名称・価格・説明・数量上限・公開状態を編集できます。",
  plansLead: "コースを編集し、含まれるオプションをスイッチで指定します。",
  inventoryLead: "日付×時間帯で利用可能な車両数を表示します。",
  permissions: "権限設定",
  permissionsLead: "管理者は役割を作成できます。店長は自店スタッフの権限を付与／解除できます。更新後すぐ反映。",
  permView: "閲覧",
  permEdit: "編集",
  newRole: "役割を追加",
  roleName: "役割名",
  assignStaff: "スタッフ権限",
  savePerms: "権限を保存",
  permSaved: "権限を保存しました。再読み込みで反映されます。",
  completeOnlyManager: "「完了」は店長または管理者のみが確定できます。",
  cancelKind: "キャンセル種別",
  voluntary: "自己都合キャンセル",
  noshow: "No-show（来店なし）",
  channelFilter: "チャネル",
  affiliateFilter: "アフィリエイト",
  allAffiliates: "すべての代理",
  affiliateField: "アフィリエイト",
  affiliateNone: "なし",
  refundAction: "返金",
  refundReserved: "返金ルールは先方確定後に実装します。操作枠のみ用意しています。",
  refundPolicy: "返金ポリシー",
  refundPolicyLead: "スタッフ／お客様向けの説明文です。課金ロジックは後ほど接続します。",
  refundPolicyPh: "出発24時間前までのキャンセルは50%返金。24時間以内またはNo-showは返金不可。",
  refundSaved: "返金ポリシーを保存しました",
  refundNote: "返金メモ",
  refundLog: "返金履歴",
  refundEmpty: "返金記録はまだありません",
  pendingList: "確認待ち（売上に含めない）",
  cancelledList: "キャンセル（売上に含めない）",
  netIncome: "チャネル手数料後の純額",
  affiliateTab: "代理手数料",
  affiliateTabHint: "第3バッチで代理ごとの件数／金額／支払手数料を入れます。",
  lastYear: "前年同月",
  cancelSplit: "キャンセル内訳",
  photos: "写真",
  photosHint: "修理伝票や損傷写真。複数枚可。",
  active: "掲載中",
};

export function b2Copy(locale: string) {
  if (locale.startsWith("ja")) return JA;
  if (locale.startsWith("en")) return EN;
  return ZH;
}

export type B2Copy = typeof ZH;

export function b2Locale(locale: string): Locale {
  if (locale.startsWith("ja")) return "ja";
  if (locale.startsWith("en")) return "en";
  return "zh";
}
