type Locale = "zh" | "en" | "ja";

const ZH = {
  units: "人",
  oversell: "⚠ 这个时段客人已超过 8 人",
  fleetHint: "点格子看谁占了人数。",
  prevWeek: "上一周",
  nextWeek: "下一周",
  thisWeek: "本周",
  prevDays: "前三天",
  nextDays: "后三天",
  theseDays: "这三天",
  closed: "休业",
  locked: "已锁",
  timeBusy: "占用",
  tightOnly: "仅看紧张",
  raceOne: "1 单",
  raceTwo: "2 单",
  bufferMark: "缓冲",
  pickStore: "全部店铺时请先选一门店。订单、日历、库存都按该店对齐。",
  slotLeft: "还能接几人",
  slotRaces: "同时几单",
  holdEmpty: "此时段没有预约。",
  holdRace: "进行中",
  holdBuffer: "赛前 / 赛后缓冲",
  holdKarts: (n: number) => `${n} 人`,
  holdMins: (n: number) => `${n} 分`,
  openOrder: "查看订单",
  newOrder: "在此时段建单",
  lockSlot: "锁定所选时段",
  unlockSlot: "解锁所选时段",
  cancelRange: "取消所选订单",
  cancelRangeAsk: (n: number) => `将取消这 ${n} 张未完成订单。确定？`,
  cancelledN: (n: number) => `已取消 ${n} 张订单。`,
  rangeEmpty: "所选时段没有可取消的订单。",
  bookBlockedDay: "这天已休业，不能建单或改到这天。",
  bookBlockedLock: "所选时间已锁定，不能建单。",
  bookBlockedHours: "不在营业时段内。",
  bookBlockedGuests: "这个时段剩余人数不够。",
  bookBlockedRaces: "这个时段已并满 2 单。",
  raceFull: "已满 8 人，不能再接",
  closeDrawer: "关闭",
  utilization: "客人占用率",
  axisDate: "日期",
  inventoryLead: "半小时一格。单击或拖选一段时间，再建立订单、取消订单或锁定。客人最多 8 人，店员留 2 台。",
  utilizationHint: "已订人数 ÷ 可接人数（客人最多 8 人，店员留 2 台）",
  included: "内置（套餐已含）",
  includedHint: "打开后前台直接列出，顾客无需加购。",
  allowed: "可加购",
  addonsMenu: "附加项管理",
  addonsLead: "独立管理附加项。可改名称、价格、描述、数量上限和上下架。",
  plansLead: "编辑套餐。附加项在编辑弹窗里添加、删除；打开内置后该项锁定，前台直接列出。",
  permissions: "权限配置",
  permissionsLead: "先定义角色能看什么、改什么，再给员工单独指定角色。",
  rolePermsTab: "角色权限",
  staffPermsTab: "员工权限",
  rolePermsLead: "勾选后点「保存权限」。自定义角色可删除。超管、店长、员工这三个系统角色不能删除。",
  staffPermsLead: "给每位员工指定角色。模块的查看 / 编辑权限在「角色权限」里定义。",
  permView: "查看",
  permEdit: "编辑",
  permModCol: "功能",
  newRole: "新建角色",
  roleName: "角色名称",
  assignStaff: "员工权限",
  savePerms: "保存权限",
  permSaved: "权限已保存。",
  deleteRole: "删除角色",
  deleteRoleAsk: "删除后，使用该角色的员工会改回「员工」。确定删除？",
  roleDeleted: "角色已删除",
  builtinNoDelete: "系统角色不能删除。",
  completeOnlyManager: "「已完成」需店长或超管确认。",
  cancelKind: "取消类型",
  voluntary: "主动取消",
  noshow: "No-show（未到店）",
  channelFilter: "渠道",
  affiliateFilter: "推广代理",
  allAffiliates: "全部代理",
  affiliateField: "推广代理",
  affiliateNone: "无",
  refundAction: "退款操作",
  refundReserved: "退款规则待甲方确认后接入。此处仅预留操作与记录。",
  refundPolicy: "退款政策",
  refundPolicyLead: "填写前台/客服可见的退款说明文本。具体扣款逻辑稍后接入。",
  refundPolicyPh: "出发前 24 小时取消退 50%。出发前不足 24 小时或 No-show 不退款。",
  refundSaved: "退款政策已保存",
  refundNote: "退款备注",
  refundLog: "退款记录",
  refundEmpty: "暂无退款记录",
  pendingList: "待确认（不计营收）",
  cancelledList: "已取消（不计营收）",
  netIncome: "渠道净收入",
  affiliateTab: "代理佣金",
  affiliateTabHint: "按代理汇总。订单数不含已取消；金额和佣金只计已完成。",
  lastYear: "去年同月",
  cancelSplit: "取消构成",
  photos: "照片",
  photosHint: "可上传维修单据或损伤照片，支持多图。",
  active: "上架",
};

const EN: typeof ZH = {
  units: "guests",
  oversell: "⚠ This slot already has more than 8 guests.",
  fleetHint: "Click a cell to see who is booked.",
  prevWeek: "Previous week",
  nextWeek: "Next week",
  thisWeek: "This week",
  prevDays: "Previous 3 days",
  nextDays: "Next 3 days",
  theseDays: "These 3 days",
  closed: "Closed",
  locked: "Locked",
  timeBusy: "Taken",
  tightOnly: "Tight only",
  raceOne: "1 booking",
  raceTwo: "2 bookings",
  bufferMark: "Buffer",
  pickStore: "Pick one shop. Orders, calendar, and inventory all follow that shop.",
  slotLeft: "Guests left",
  slotRaces: "Bookings now",
  holdEmpty: "No booking in this slot.",
  holdRace: "On course",
  holdBuffer: "Pre / post buffer",
  holdKarts: (n: number) => `${n} guests`,
  holdMins: (n: number) => `${n} min`,
  openOrder: "Open order",
  newOrder: "New booking here",
  lockSlot: "Lock selected slots",
  unlockSlot: "Unlock selected slots",
  cancelRange: "Cancel orders in range",
  cancelRangeAsk: (n: number) => `Cancel these ${n} open bookings?`,
  cancelledN: (n: number) => `Cancelled ${n} bookings.`,
  rangeEmpty: "No open bookings in this range.",
  bookBlockedDay: "The shop is closed that day.",
  bookBlockedLock: "That time is locked. Cannot book.",
  bookBlockedHours: "Outside opening hours.",
  bookBlockedGuests: "Not enough guest seats left.",
  bookBlockedRaces: "Already 2 bookings in that slot.",
  raceFull: "8 guests already. Cannot take more.",
  closeDrawer: "Close",
  utilization: "Guest fill rate",
  axisDate: "Date",
  inventoryLead: "Each cell is 30 minutes. Click or drag a range, then book, cancel, or lock. Max 8 guests. 2 karts stay for staff.",
  utilizationHint: "Booked guests ÷ guest cap (max 8 guests, 2 karts held for staff)",
  included: "Included in plan",
  includedHint: "Shown as included. Guests do not purchase these.",
  allowed: "Optional extras",
  addonsMenu: "Add-ons",
  addonsLead: "Edit name, price, description, quantity cap, and listing status.",
  plansLead: "Edit plans here. Add or remove add-ons in the editor. Included items lock and list with the plan.",
  permissions: "Permissions",
  permissionsLead: "Define what each role can view or edit, then assign a role to each staff member.",
  rolePermsTab: "Role permissions",
  staffPermsTab: "Staff access",
  rolePermsLead: "Click Save after changing checkboxes. Custom roles can be deleted. Admin, Manager and Staff cannot.",
  staffPermsLead: "Assign a role to each person. Module view / edit rights are set under Role permissions.",
  permView: "View",
  permEdit: "Edit",
  permModCol: "Module",
  newRole: "New role",
  roleName: "Role name",
  assignStaff: "Staff access",
  savePerms: "Save permissions",
  permSaved: "Permissions saved.",
  deleteRole: "Delete role",
  deleteRoleAsk: "Staff on this role will fall back to Staff. Delete this role?",
  roleDeleted: "Role deleted.",
  builtinNoDelete: "Built-in roles cannot be deleted.",
  completeOnlyManager: "Only a manager or admin can mark an order completed.",
  cancelKind: "Cancel type",
  voluntary: "Guest cancelled",
  noshow: "No-show",
  channelFilter: "Channel",
  affiliateFilter: "Affiliate",
  allAffiliates: "All affiliates",
  affiliateField: "Affiliate",
  affiliateNone: "None",
  refundAction: "Refund",
  refundReserved: "Refund rules will be filled in after the client confirms them.",
  refundPolicy: "Refund policy",
  refundPolicyLead: "Policy text for staff and guests. Charge logic comes later.",
  refundPolicyPh: "Cancel 24h before departure: 50% refund. Inside 24h or no-show: no refund.",
  refundSaved: "Refund policy saved",
  refundNote: "Refund note",
  refundLog: "Refund log",
  refundEmpty: "No refund records yet",
  pendingList: "Pending (not in revenue)",
  cancelledList: "Cancelled (not in revenue)",
  netIncome: "Net after channel cut",
  affiliateTab: "Affiliate commission",
  affiliateTabHint: "Totals per agent. Order count excludes cancelled. Amount and commission count completed only.",
  lastYear: "Same month last year",
  cancelSplit: "Cancellations",
  photos: "Photos",
  photosHint: "Repair slips or damage photos. Multiple images allowed.",
  active: "Listed",
};

const JA: typeof ZH = {
  units: "人",
  oversell: "⚠ この時間のお客様が8人を超えています。",
  fleetHint: "マスをクリックすると、誰が予約しているか分かります。",
  prevWeek: "前週",
  nextWeek: "翌週",
  thisWeek: "今週",
  prevDays: "前3日",
  nextDays: "翌3日",
  theseDays: "この3日",
  closed: "休業",
  locked: "ロック中",
  timeBusy: "予約済",
  tightOnly: "逼迫のみ",
  raceOne: "1件",
  raceTwo: "2件",
  bufferMark: "バッファ",
  pickStore: "全店舗では店舗を1つ選んでください。予約・カレンダー・在庫がその店に揃います。",
  slotLeft: "まだ受けられる人数",
  slotRaces: "同時の予約",
  holdEmpty: "この時間に予約はありません。",
  holdRace: "走行中",
  holdBuffer: "前後30分",
  holdKarts: (n: number) => `${n}人`,
  holdMins: (n: number) => `${n}分`,
  openOrder: "注文を開く",
  newOrder: "この時間で新規予約",
  lockSlot: "選択枠をロック",
  unlockSlot: "選択枠のロック解除",
  cancelRange: "選択範囲の注文を取消",
  cancelRangeAsk: (n: number) => `未完了の注文 ${n} 件を取り消します。よろしいですか？`,
  cancelledN: (n: number) => `${n} 件を取り消しました。`,
  rangeEmpty: "この範囲に取り消せる注文はありません。",
  bookBlockedDay: "その日は休業です。",
  bookBlockedLock: "その時間はロックされています。",
  bookBlockedHours: "営業時間外です。",
  bookBlockedGuests: "残席が足りません。",
  bookBlockedRaces: "この時間はすでに2件です。",
  raceFull: "すでに8人です。これ以上受けられません。",
  closeDrawer: "閉じる",
  utilization: "お客様の埋まり",
  axisDate: "日付",
  inventoryLead: "30分マスです。クリックまたはドラッグで範囲を選び、予約追加・取消・ロックができます。お客様は最大8人。スタッフ用に2台残します。",
  utilizationHint: "予約人数 ÷ 受けられる人数（お客様最大8人、スタッフ用2台）",
  included: "セットに含む",
  includedHint: "オンにするとフロントに含まれている表示になり、追加購入しません。",
  allowed: "追加オプション",
  addonsMenu: "オプション管理",
  addonsLead: "名称・価格・説明・数量上限・公開状態を編集できます。",
  plansLead: "コースを編集します。オプションの追加・削除は編集画面で行います。セットに含むをオンにすると行がロックされます。",
  permissions: "権限設定",
  permissionsLead: "役割の閲覧／編集を定義してから、スタッフに役割を割り当てます。",
  rolePermsTab: "役割権限",
  staffPermsTab: "スタッフ権限",
  rolePermsLead: "チェック後は「権限を保存」を押してください。カスタム役割は削除できます。管理者・店長・スタッフは削除できません。",
  staffPermsLead: "スタッフごとに役割を指定します。モジュールの閲覧／編集は「役割権限」で定義します。",
  permView: "閲覧",
  permEdit: "編集",
  permModCol: "機能",
  newRole: "役割を追加",
  roleName: "役割名",
  assignStaff: "スタッフ権限",
  savePerms: "権限を保存",
  permSaved: "権限を保存しました。",
  deleteRole: "役割を削除",
  deleteRoleAsk: "この役割のスタッフは「スタッフ」に戻ります。削除しますか？",
  roleDeleted: "役割を削除しました。",
  builtinNoDelete: "システム役割は削除できません。",
  completeOnlyManager: "「完了」は店長または管理者のみが確定できます。",
  cancelKind: "キャンセル種別",
  voluntary: "自己都合キャンセル",
  noshow: "No-show（来店なし）",
  channelFilter: "チャネル",
  affiliateFilter: "アフィリエイト",
  allAffiliates: "すべての代理",
  affiliateField: "アフィリエイト",
  affiliateNone: "なし",
  refundAction: "返金",
  refundReserved: "返金ルールは先方確定後に実装します。操作枠のみ用意しています。",
  refundPolicy: "返金ポリシー",
  refundPolicyLead: "スタッフ／お客様向けの説明文です。課金ロジックは後ほど接続します。",
  refundPolicyPh: "出発24時間前までのキャンセルは50%返金。24時間以内またはNo-showは返金不可。",
  refundSaved: "返金ポリシーを保存しました",
  refundNote: "返金メモ",
  refundLog: "返金履歴",
  refundEmpty: "返金記録はまだありません",
  pendingList: "確認待ち（売上に含めない）",
  cancelledList: "キャンセル（売上に含めない）",
  netIncome: "チャネル手数料後の純額",
  affiliateTab: "代理手数料",
  affiliateTabHint: "代理ごとに集計。件数はキャンセル除外。金額と手数料は完了のみ。",
  lastYear: "前年同月",
  cancelSplit: "キャンセル内訳",
  photos: "写真",
  photosHint: "修理伝票や損傷写真。複数枚可。",
  active: "掲載中",
};

export function b2Copy(locale: string) {
  if (locale.startsWith("ja")) return JA;
  if (locale.startsWith("en")) return EN;
  return ZH;
}

export type B2Copy = typeof ZH;

export function bookBlockedText(locale: string, reason: "day" | "lock" | "hours" | "guests" | "races") {
  const b2 = b2Copy(locale);
  if (reason === "day") return b2.bookBlockedDay;
  if (reason === "lock") return b2.bookBlockedLock;
  if (reason === "hours") return b2.bookBlockedHours;
  if (reason === "guests") return b2.bookBlockedGuests;
  return b2.bookBlockedRaces;
}

export function b2Locale(locale: string): Locale {
  if (locale.startsWith("ja")) return "ja";
  if (locale.startsWith("en")) return "en";
  return "zh";
}
