type Locale = "zh" | "en" | "ja";

const ZH = {
  channelsLead: "B2B 渠道列表。可按名称或联系人搜索，并按类型、抽成、状态排序筛选。",
  channelKind: "类型",
  channelContact: "联系人",
  channelStatus: "状态",
  kindAll: "全部类型",
  kindOta: "OTA",
  kindHotel: "酒店",
  kindSocial: "社媒",
  kindDirect: "直营",
  kindOther: "其他",
  searchChannel: "搜索名称或联系人",
  editChannel: "编辑渠道",
  affiliatesLead: "B2C 推广代理。新增后自动生成推广码，详情页可下载链接二维码和海报。",
  email: "邮箱",
  phone: "电话",
  password: "登录密码",
  passwordHint: "代理后台登录用。演示默认 agent123。",
  searchAffiliate: "搜索姓名、邮箱或电话",
  statusAll: "全部状态",
  commission: "累计佣金",
  copyLink: "复制链接",
  copied: "已复制",
  qr: "推广二维码",
  downloadQr: "下载二维码",
  posters: "推广海报",
  posterCustom: "上传自定义海报模板",
  posterCustomHint: "自定义模板上传预留给甲方。当前可先用下方三套默认海报。",
  posterDl: "下载海报",
  autoCode: "保存后按姓名自动生成",
  loginFail: "邮箱或密码不对，或账号已停用。",
  agentLogin: "推广代理登录",
  agentLead: "独立入口，只能查看自己的订单、佣金和海报。",
  agentHint: "演示：yuki@agent.test / agent123",
  agentHome: "代理工作台",
  myInfo: "我的资料",
  myOrders: "带来的订单",
  myCut: "佣金明细",
  logout: "退出",
  noOrders: "还没有通过你的推广码完成的订单。",
  cutDue: "应发佣金",
  orderAmount: "已完成金额",
  reportOrders: "订单数",
  reportAmount: "总金额",
  reportCut: "应发佣金",
  affiliateTabHint: "按代理汇总。订单数不含已取消；金额和佣金只计已完成。",
  emptyList: "没有符合条件的记录",
};

const EN: typeof ZH = {
  channelsLead: "B2B channel list. Search by name or contact. Sort and filter by type, cut, and status.",
  channelKind: "Type",
  channelContact: "Contact",
  channelStatus: "Status",
  kindAll: "All types",
  kindOta: "OTA",
  kindHotel: "Hotel",
  kindSocial: "Social",
  kindDirect: "Direct",
  kindOther: "Other",
  searchChannel: "Search name or contact",
  editChannel: "Edit channel",
  affiliatesLead: "B2C promo agents. New agents get a code automatically. Open one to download the QR and posters.",
  email: "Email",
  phone: "Phone",
  password: "Password",
  passwordHint: "Used for the agent portal. Demo default is agent123.",
  searchAffiliate: "Search name, email, or phone",
  statusAll: "All status",
  commission: "Commission",
  copyLink: "Copy link",
  copied: "Copied",
  qr: "Promo QR",
  downloadQr: "Download QR",
  posters: "Posters",
  posterCustom: "Upload custom poster",
  posterCustomHint: "Custom templates are reserved for the client. Use the three default posters for now.",
  posterDl: "Download poster",
  autoCode: "Generated from the name on save",
  loginFail: "Wrong email or password, or the account is paused.",
  agentLogin: "Affiliate login",
  agentLead: "Separate portal. You only see your own orders, commission, and posters.",
  agentHint: "Demo: yuki@agent.test / agent123",
  agentHome: "Affiliate desk",
  myInfo: "My profile",
  myOrders: "Referred orders",
  myCut: "Commission",
  logout: "Log out",
  noOrders: "No orders have come through your code yet.",
  cutDue: "Commission due",
  orderAmount: "Completed amount",
  reportOrders: "Orders",
  reportAmount: "Amount",
  reportCut: "Commission due",
  affiliateTabHint: "Totals per agent. Order count excludes cancelled. Amount and commission count completed only.",
  emptyList: "No matching rows",
};

const JA: typeof ZH = {
  channelsLead: "B2Bチャネル一覧。名前・連絡先で検索し、種別・手数料・状態で並べ替えできます。",
  channelKind: "種別",
  channelContact: "連絡先",
  channelStatus: "状態",
  kindAll: "すべての種別",
  kindOta: "OTA",
  kindHotel: "ホテル",
  kindSocial: "SNS",
  kindDirect: "直営",
  kindOther: "その他",
  searchChannel: "名前または連絡先",
  editChannel: "チャネルを編集",
  affiliatesLead: "B2C紹介代理。追加時にコードを自動発行。詳細からQRとポスターをダウンロードできます。",
  email: "メール",
  phone: "電話",
  password: "パスワード",
  passwordHint: "代理ポータル用。デモ初期値は agent123。",
  searchAffiliate: "名前・メール・電話で検索",
  statusAll: "すべての状態",
  commission: "累計手数料",
  copyLink: "リンクをコピー",
  copied: "コピーしました",
  qr: "紹介QR",
  downloadQr: "QRをダウンロード",
  posters: "ポスター",
  posterCustom: "カスタムポスターをアップロード",
  posterCustomHint: "カスタムテンプレートは先方アップロード用です。当面は下の3種をご利用ください。",
  posterDl: "ポスターをダウンロード",
  autoCode: "保存時に名前から自動生成",
  loginFail: "メールまたはパスワードが違うか、停止中です。",
  agentLogin: "紹介代理ログイン",
  agentLead: "独立入口です。自分の予約・手数料・ポスターのみ見られます。",
  agentHint: "デモ：yuki@agent.test / agent123",
  agentHome: "代理デスク",
  myInfo: "プロフィール",
  myOrders: "紹介した予約",
  myCut: "手数料明細",
  logout: "ログアウト",
  noOrders: "あなたのコード経由の予約はまだありません。",
  cutDue: "支払手数料",
  orderAmount: "完了金額",
  reportOrders: "件数",
  reportAmount: "金額",
  reportCut: "支払手数料",
  affiliateTabHint: "代理ごとに集計。件数はキャンセル除外。金額と手数料は完了のみ。",
  emptyList: "該当する行がありません",
};

export function b3Copy(locale: string) {
  if (locale.startsWith("ja")) return JA;
  if (locale.startsWith("en")) return EN;
  return ZH;
}

export type B3Copy = typeof ZH;
export type { Locale as B3Locale };
